version: '3.8'

services:
  banco-de-dados:
    image: postgres:15
    container_name: senha_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: gerenciador_senhas
    ports:
      - "5432:5432"
